export interface AudioTrack {
  id: string;
  title: string;
  artist: string;
  category: "classical" | "chanson" | "meditation" | "nature";
  categoryLabel: string;
  genreEn: string;
  genreKo: string;
  src: string;
  duration?: string;
  icon?: string;
}

export interface MusicGenre {
  id: string;
  labelEn: string;
  labelKo: string;
  icon: string;
  descriptionEn: string;
  descriptionKo: string;
}

export const MUSIC_GENRES: MusicGenre[] = [
  {
    id: "all",
    labelEn: "All Genres (40 Tracks)",
    labelKo: "전체 장르 (40곡)",
    icon: "LayoutGrid",
    descriptionEn: "Complete 40-track continuous stream of 100% distinct authentic master recordings",
    descriptionKo: "100% 개별 고유 음원으로 구성된 클래식, 샹송, 528Hz 명상 및 자연음 40곡",
  },
  {
    id: "classical",
    labelEn: "Classical Masterpieces (10)",
    labelKo: "바흐·비발디·쇼팽 클래식 (10곡)",
    icon: "Music",
    descriptionEn: "10 distinct authentic recordings: Bach, Vivaldi Four Seasons, Chopin, Satie & Beethoven",
    descriptionKo: "바흐 G선상/첼로/골드베르크, 비발디 봄/여름/겨울, 쇼팽 녹턴, 사티, 베토벤 월광 10곡",
  },
  {
    id: "chanson",
    labelEn: "Parisian Chanson & Cafe (10)",
    labelKo: "북카페 & 파리지앵 샹송 (10곡)",
    icon: "Coffee",
    descriptionEn: "10 distinct French musette waltzes, cafe accordions, acoustic guitar & serenades",
    descriptionKo: "프렌치 뮈제트 아코디언, 센강 왈츠, 클래식 기타 캐논, 슈베르트/엘가 세레나데 10곡",
  },
  {
    id: "meditation",
    labelEn: "528Hz Alpha Meditation (10)",
    labelKo: "528Hz 딥포커스 명상 (10곡)",
    icon: "Sparkles",
    descriptionEn: "10 distinct brainwave & mindfulness recordings: Tibetan singing bowl, 528Hz & Debussy",
    descriptionKo: "티베트 싱잉볼, 528Hz 솔페지오, 드뷔시 달빛 현악, 비발디 아다지오 이완 사운드 10곡",
  },
  {
    id: "nature",
    labelEn: "Nature & Rain Sanctuary (10)",
    labelKo: "자연의 소리 & 빗소리 (10곡)",
    icon: "CloudRain",
    descriptionEn: "10 distinct field recordings: Window rain, Bourne Woods birdsong, storm thunder & ocean",
    descriptionKo: "도서관 빗소리, 태평양 파도, 영국 본우즈 아침 새소리, 천둥 빗소리, 여름밤 귀뚜라미 10곡",
  },
];

export const READING_AUDIO_TRACKS: AudioTrack[] = [
  // ==============================================================
  // 1. CLASSICAL PIANO & STRINGS (10 100% DISTINCT RECORDINGS)
  // ==============================================================
  {
    id: "bach-air-on-g-string",
    title: "Bach - Air on the G String (BWV 1068)",
    artist: "J.S. Bach (US Air Force Strings)",
    category: "classical",
    categoryLabel: "바흐 현악 🎻",
    genreEn: "Classical Masterpieces",
    genreKo: "클래식 명곡",
    src: "/audio/classical/bach-air-on-g-string.mp3",
    duration: "4:32",
    icon: "Music",
  },
  {
    id: "bach-cello-suite",
    title: "Bach - Cello Suite No. 1 in G major (Prelude)",
    artist: "J.S. Bach (Solo Cello - John Michel)",
    category: "classical",
    categoryLabel: "바흐 첼로 🎻",
    genreEn: "Classical Masterpieces",
    genreKo: "클래식 명곡",
    src: "/audio/classical/bach-cello-suite.ogg",
    duration: "2:50",
    icon: "Music",
  },
  {
    id: "bach-goldberg",
    title: "Bach - Goldberg Variations: Aria (BWV 988)",
    artist: "J.S. Bach (Grand Piano - Kimiko Ishizaka)",
    category: "classical",
    categoryLabel: "바흐 골드베르크 🎹",
    genreEn: "Classical Masterpieces",
    genreKo: "클래식 명곡",
    src: "/audio/classical/bach-goldberg.ogg",
    duration: "4:15",
    icon: "Music",
  },
  {
    id: "bach-minuet",
    title: "Bach - Minuet in G major (BWV Anh. 114)",
    artist: "J.S. Bach (Notebook for Anna Magdalena)",
    category: "classical",
    categoryLabel: "바흐 미뉴에트 🎹",
    genreEn: "Classical Masterpieces",
    genreKo: "클래식 명곡",
    src: "/audio/classical/bach-minuet.ogg",
    duration: "1:40",
    icon: "Music",
  },
  {
    id: "vivaldi-spring",
    title: "Vivaldi - Four Seasons: Spring (La Primavera - Allegro)",
    artist: "Antonio Vivaldi (John Harrison Violin)",
    category: "classical",
    categoryLabel: "비발디 사계 봄 🌸",
    genreEn: "Classical Masterpieces",
    genreKo: "클래식 명곡",
    src: "/audio/classical/vivaldi-spring.oga",
    duration: "3:36",
    icon: "Music",
  },
  {
    id: "vivaldi-summer",
    title: "Vivaldi - Four Seasons: Summer (L'Estate - Storm Presto)",
    artist: "Antonio Vivaldi (John Harrison Violin)",
    category: "classical",
    categoryLabel: "비발디 사계 여름 ⚡",
    genreEn: "Classical Masterpieces",
    genreKo: "클래식 명곡",
    src: "/audio/classical/vivaldi-summer.oga",
    duration: "2:45",
    icon: "Music",
  },
  {
    id: "vivaldi-winter",
    title: "Vivaldi - Four Seasons: Winter (L'Inverno - Allegro)",
    artist: "Antonio Vivaldi (John Harrison Violin)",
    category: "classical",
    categoryLabel: "비발디 사계 겨울 ❄️",
    genreEn: "Classical Masterpieces",
    genreKo: "클래식 명곡",
    src: "/audio/classical/vivaldi-winter.oga",
    duration: "3:29",
    icon: "Music",
  },
  {
    id: "chopin-nocturne",
    title: "Chopin - Nocturne in E-flat major, Op. 9 No. 2",
    artist: "Frédéric Chopin (Concert Grand Piano)",
    category: "classical",
    categoryLabel: "쇼팽 녹턴 🎹",
    genreEn: "Classical Masterpieces",
    genreKo: "클래식 명곡",
    src: "/audio/classical/chopin-nocturne.ogg",
    duration: "4:30",
    icon: "Music",
  },
  {
    id: "satie-gymnopedie",
    title: "Erik Satie - Gymnopédie No. 1 (Lent et douloureux)",
    artist: "Erik Satie (Acoustic Solo Piano)",
    category: "classical",
    categoryLabel: "사티 짐노페디 🎹",
    genreEn: "Classical Masterpieces",
    genreKo: "클래식 명곡",
    src: "/audio/classical/satie-gymnopedie.ogg",
    duration: "3:10",
    icon: "Music",
  },
  {
    id: "beethoven-moonlight",
    title: "Beethoven - Moonlight Sonata (Op. 27 No. 2 - Allegretto)",
    artist: "Ludwig van Beethoven (Solo Grand Piano)",
    category: "classical",
    categoryLabel: "베토벤 월광 🎹",
    genreEn: "Classical Masterpieces",
    genreKo: "클래식 명곡",
    src: "/audio/classical/beethoven-moonlight.ogg",
    duration: "2:15",
    icon: "Music",
  },

  // ==============================================================
  // 2. PARISIAN CHANSON & CAFE (10 100% DISTINCT RECORDINGS)
  // ==============================================================
  {
    id: "chanson-accordion",
    title: "Duet Musette (Parisian Cafe Accordion)",
    artist: "French Accordion & Acoustic Ensemble",
    category: "chanson",
    categoryLabel: "북카페 샹송 ☕",
    genreEn: "Parisian Chanson",
    genreKo: "파리지앵 샹송",
    src: "/audio/classical/chanson-accordion.mp3",
    duration: "3:10",
    icon: "Coffee",
  },
  {
    id: "chanson-seine-walk",
    title: "The Sirens Waltz (Vintage French Musette)",
    artist: "Paris Accordion & Salon Orchestra",
    category: "chanson",
    categoryLabel: "센 강 산책 🍷",
    genreEn: "Parisian Chanson",
    genreKo: "파리지앵 샹송",
    src: "/audio/classical/chanson-seine-walk.ogg",
    duration: "1:55",
    icon: "Coffee",
  },
  {
    id: "chanson-french-waltz",
    title: "Chopin - Grand Valse in A-flat major, Op. 64 No. 3",
    artist: "Salon Piano of Paris",
    category: "chanson",
    categoryLabel: "파리 살롱 왈츠 🥐",
    genreEn: "Parisian Chanson",
    genreKo: "파리지앵 샹송",
    src: "/audio/classical/chanson-french-waltz.oga",
    duration: "3:20",
    icon: "Coffee",
  },
  {
    id: "chanson-musette",
    title: "Rameau - Musette de la Suite en Mi",
    artist: "French Baroque Ensemble",
    category: "chanson",
    categoryLabel: "프렌치 뮈제트 🎻",
    genreEn: "Parisian Chanson",
    genreKo: "파리지앵 샹송",
    src: "/audio/classical/chanson-musette.ogg",
    duration: "4:15",
    icon: "Coffee",
  },
  {
    id: "chanson-guitar-canon",
    title: "Pachelbel - Canon in D major (Solo Classical Guitar)",
    artist: "Boutique Cafe Nylon Guitar",
    category: "chanson",
    categoryLabel: "카페 기타 캐논 🎸",
    genreEn: "Parisian Chanson",
    genreKo: "파리지앵 샹송",
    src: "/audio/classical/chanson-guitar-canon.ogg",
    duration: "2:40",
    icon: "Coffee",
  },
  {
    id: "chanson-serenade",
    title: "Schubert - Ständchen Serenade (D. 957 No. 4)",
    artist: "Jason Han (Solo Piano)",
    category: "chanson",
    categoryLabel: "슈베르트 세레나데 🌙",
    genreEn: "Parisian Chanson",
    genreKo: "파리지앵 샹송",
    src: "/audio/classical/chanson-serenade.ogg",
    duration: "4:00",
    icon: "Coffee",
  },
  {
    id: "chanson-mozart-romanze",
    title: "Mozart - Serenade No. 13 in G major: Romanze",
    artist: "Baroque Strings of Vienna",
    category: "chanson",
    categoryLabel: "모차르트 로망스 ☕",
    genreEn: "Parisian Chanson",
    genreKo: "파리지앵 샹송",
    src: "/audio/classical/chanson-mozart-romanze.ogg",
    duration: "5:30",
    icon: "Coffee",
  },
  {
    id: "chanson-brahms-lullaby",
    title: "Brahms - Wiegenlied Lullaby (Op. 49 No. 4)",
    artist: "Acoustic Chamber Strings",
    category: "chanson",
    categoryLabel: "브람스 자장가 🌿",
    genreEn: "Parisian Chanson",
    genreKo: "파리지앵 샹송",
    src: "/audio/classical/chanson-brahms-lullaby.ogg",
    duration: "2:10",
    icon: "Coffee",
  },
  {
    id: "chanson-elgar-serenade",
    title: "Elgar - Serenade for Strings in E minor (Op. 20)",
    artist: "Chamber Strings Ensemble",
    category: "chanson",
    categoryLabel: "엘가 현악 세레나데 🎻",
    genreEn: "Parisian Chanson",
    genreKo: "파리지앵 샹송",
    src: "/audio/classical/chanson-elgar-serenade.ogg",
    duration: "3:40",
    icon: "Coffee",
  },
  {
    id: "chanson-autumn-allegro",
    title: "Vivaldi - Four Seasons: Autumn (L'Autunno - Allegro)",
    artist: "John Harrison Violin & Orchestra",
    category: "chanson",
    categoryLabel: "비발디 사계 가을 🍂",
    genreEn: "Parisian Chanson",
    genreKo: "파리지앵 샹송",
    src: "/audio/classical/chanson-autumn-allegro.oga",
    duration: "3:25",
    icon: "Coffee",
  },

  // ==============================================================
  // 3. 528Hz ALPHA MEDITATION (10 100% DISTINCT RECORDINGS)
  // ==============================================================
  {
    id: "meditation-tibetan-bowl",
    title: "Authentic Tibetan Singing Bowl Harmonic Resonance",
    artist: "Himalayan Monastery Monks",
    category: "meditation",
    categoryLabel: "티베트 싱잉볼 🥣",
    genreEn: "528Hz Meditation",
    genreKo: "528Hz 명상",
    src: "/audio/classical/meditation-tibetan-bowl.ogg",
    duration: "1:30",
    icon: "Sparkles",
  },
  {
    id: "meditation-528hz",
    title: "528Hz Alpha Brainwave Deep Reading Focus",
    artist: "Solfeggio Cognitive Flow",
    category: "meditation",
    categoryLabel: "528Hz 몰입 독서 🧘",
    genreEn: "528Hz Meditation",
    genreKo: "528Hz 명상",
    src: "/audio/classical/meditation-528hz.mp3",
    duration: "5:00",
    icon: "Sparkles",
  },
  {
    id: "meditation-clair-de-lune",
    title: "Debussy - Clair de Lune (Gentle Ambient Strings)",
    artist: "WikiOrchestra Violins & Strings",
    category: "meditation",
    categoryLabel: "드뷔시 달빛 현악 🌌",
    genreEn: "528Hz Meditation",
    genreKo: "528Hz 명상",
    src: "/audio/classical/meditation-clair-de-lune.ogg",
    duration: "4:50",
    icon: "Sparkles",
  },
  {
    id: "meditation-summer-adagio",
    title: "Vivaldi - Adagio Deep Relaxation Strings",
    artist: "John Harrison Solo Violin & Strings",
    category: "meditation",
    categoryLabel: "비발디 아다지오 이완 🕊️",
    genreEn: "528Hz Meditation",
    genreKo: "528Hz 명상",
    src: "/audio/classical/meditation-summer-adagio.oga",
    duration: "2:20",
    icon: "Sparkles",
  },
  {
    id: "meditation-432hz-miracle",
    title: "432Hz Miracle Harmonic Serenity",
    artist: "Sacred Sound Architecture",
    category: "meditation",
    categoryLabel: "432Hz 미라클 톤 ✨",
    genreEn: "528Hz Meditation",
    genreKo: "528Hz 명상",
    src: "/audio/classical/meditation-432hz-miracle.mp3",
    duration: "4:30",
    icon: "Sparkles",
  },
  {
    id: "meditation-solfeggio-clarity",
    title: "528Hz Solfeggio Mind Clarity & Neural Focus",
    artist: "Binaural Cognitive Lab",
    category: "meditation",
    categoryLabel: "528Hz 멘탈 포커스 🧠",
    genreEn: "528Hz Meditation",
    genreKo: "528Hz 명상",
    src: "/audio/classical/meditation-solfeggio-clarity.mp3",
    duration: "4:45",
    icon: "Sparkles",
  },
  {
    id: "meditation-theta-flow",
    title: "Deep Theta Subconscious Stillness",
    artist: "Theta Flow Frequency",
    category: "meditation",
    categoryLabel: "세타파 딥 플로우 🌊",
    genreEn: "528Hz Meditation",
    genreKo: "528Hz 명상",
    src: "/audio/classical/meditation-theta-flow.mp3",
    duration: "5:15",
    icon: "Sparkles",
  },
  {
    id: "meditation-zen-garden",
    title: "Zen Garden Water & Temple Chimes",
    artist: "Kyoto Meditation Sanctuary",
    category: "meditation",
    categoryLabel: "교토 젠 가든 🎋",
    genreEn: "528Hz Meditation",
    genreKo: "528Hz 명상",
    src: "/audio/classical/meditation-zen-garden.mp3",
    duration: "4:50",
    icon: "Sparkles",
  },
  {
    id: "meditation-alpha-healing",
    title: "528Hz Cellular Healing Relaxation",
    artist: "Integrative Frequency Stream",
    category: "meditation",
    categoryLabel: "528Hz 힐링 스트림 🌟",
    genreEn: "528Hz Meditation",
    genreKo: "528Hz 명상",
    src: "/audio/classical/meditation-alpha-healing.mp3",
    duration: "5:10",
    icon: "Sparkles",
  },
  {
    id: "meditation-astral-serenity",
    title: "Astral Horizon Cosmic Peace",
    artist: "Cosmic Tone Resonance",
    category: "meditation",
    categoryLabel: "코스믹 고요 🌌",
    genreEn: "528Hz Meditation",
    genreKo: "528Hz 명상",
    src: "/audio/classical/meditation-astral-serenity.mp3",
    duration: "5:40",
    icon: "Sparkles",
  },

  // ==============================================================
  // 4. NATURE & RAIN SANCTUARY (10 100% DISTINCT RECORDINGS)
  // ==============================================================
  {
    id: "nature-rain",
    title: "Gentle Rain on Library Windowpane",
    artist: "Ambient Nature Sanctuary",
    category: "nature",
    categoryLabel: "도서관 빗소리 🌧️",
    genreEn: "Nature Sanctuary",
    genreKo: "자연 빗소리",
    src: "/audio/classical/nature-rain.mp3",
    duration: "6:10",
    icon: "CloudRain",
  },
  {
    id: "nature-ocean",
    title: "Calm Ocean Waves & Horizon Breeze",
    artist: "Pacific Coastal Calming Sound",
    category: "nature",
    categoryLabel: "온화한 파도소리 🌊",
    genreEn: "Nature Sanctuary",
    genreKo: "자연 파도소리",
    src: "/audio/classical/nature-ocean.mp3",
    duration: "5:30",
    icon: "CloudRain",
  },
  {
    id: "nature-forest-birdsong",
    title: "Authentic Bourne Woods Morning Birdsong",
    artist: "Bourne Woods Alpine Habitat",
    category: "nature",
    categoryLabel: "영국 숲속 새소리 🌲",
    genreEn: "Nature Sanctuary",
    genreKo: "자연 새소리",
    src: "/audio/classical/nature-forest-birdsong.mp3",
    duration: "1:55",
    icon: "CloudRain",
  },
  {
    id: "nature-thunder-rain",
    title: "Concrete Patio Storm & Distant Thunder",
    artist: "Authentic Storm Audio Capture",
    category: "nature",
    categoryLabel: "폭우 & 천둥소리 ⚡",
    genreEn: "Nature Sanctuary",
    genreKo: "천둥 빗소리",
    src: "/audio/classical/nature-thunder-rain.ogg",
    duration: "4:20",
    icon: "CloudRain",
  },
  {
    id: "nature-night-crickets",
    title: "Dordogne Pond Summer Crickets & Night Sky",
    artist: "French Countryside Night Ambiance",
    category: "nature",
    categoryLabel: "도르도뉴 밤 귀뚜라미 🦗",
    genreEn: "Nature Sanctuary",
    genreKo: "밤 귀뚜라미",
    src: "/audio/classical/nature-night-crickets.ogg",
    duration: "2:45",
    icon: "CloudRain",
  },
  {
    id: "nature-night-rain-crickets",
    title: "Chiang Mai Rainforest Night Creatures & Rain",
    artist: "Northern Thailand Highland Sanctuary",
    category: "nature",
    categoryLabel: "열대 숲 야간 빗소리 🌴",
    genreEn: "Nature Sanctuary",
    genreKo: "열대야 빗소리",
    src: "/audio/classical/nature-night-rain-crickets.ogg",
    duration: "2:05",
    icon: "CloudRain",
  },
  {
    id: "nature-fireplace-thunder",
    title: "Cozy Hearth Crackling Fireplace",
    artist: "Warm Library Fireplace Acoustics",
    category: "nature",
    categoryLabel: "서재 벽난로 장작불 🪵",
    genreEn: "Nature Sanctuary",
    genreKo: "벽난로 소리",
    src: "/audio/classical/nature-fireplace-thunder.mp3",
    duration: "6:20",
    icon: "CloudRain",
  },
  {
    id: "nature-mountain-stream",
    title: "Crystal Mountain Stream & Forest Water",
    artist: "Highland Flowing Water Sounds",
    category: "nature",
    categoryLabel: "맑은 계곡물 소리 🏞️",
    genreEn: "Nature Sanctuary",
    genreKo: "계곡물 소리",
    src: "/audio/classical/nature-mountain-stream.mp3",
    duration: "5:15",
    icon: "CloudRain",
  },
  {
    id: "nature-bamboo-breeze",
    title: "Bamboo Grove Wind Whispers",
    artist: "Asian Wind Sanctuary",
    category: "nature",
    categoryLabel: "대나무 숲 바람 🎋",
    genreEn: "Nature Sanctuary",
    genreKo: "대나무 바람소리",
    src: "/audio/classical/nature-bamboo-breeze.mp3",
    duration: "5:05",
    icon: "CloudRain",
  },
  {
    id: "nature-sunrise-breeze",
    title: "Horizon Dawn Meadow Birds & Gentle Wind",
    artist: "Early Morning Solitude",
    category: "nature",
    categoryLabel: "새벽 풀밭 미풍 🌅",
    genreEn: "Nature Sanctuary",
    genreKo: "새벽바람 소리",
    src: "/audio/classical/nature-sunrise-breeze.mp3",
    duration: "4:30",
    icon: "CloudRain",
  },
];

export const RELAXING_AUDIO_TRACKS = READING_AUDIO_TRACKS;
