export interface AudioTrack {
  id: string;
  title: string;
  artist: string;
  category: "classical" | "chanson" | "meditation" | "nature";
  categoryLabel: string;
  genreEn: string;
  genreKo: string;
  src: string;
  duration?: string;
  icon?: string;
}

export interface MusicGenre {
  id: string;
  labelEn: string;
  labelKo: string;
  icon: string;
  descriptionEn: string;
  descriptionKo: string;
}

export const MUSIC_GENRES: MusicGenre[] = [
  {
    id: "all",
    labelEn: "All Genres (40 Tracks)",
    labelKo: "전체 장르 (40곡)",
    icon: "LayoutGrid",
    descriptionEn: "Complete 40-track continuous stream across Classical, Chanson, 528Hz & Nature",
    descriptionKo: "클래식, 샹송, 528Hz 명상 및 자연음 40곡 전곡 연속 재생",
  },
  {
    id: "classical",
    labelEn: "Classical Masterpieces (10)",
    labelKo: "바흐·비발디·쇼팽 클래식 (10곡)",
    icon: "Music",
    descriptionEn: "Authentic studio recordings of Bach, Vivaldi Four Seasons, Chopin & Satie",
    descriptionKo: "바흐 G선상의 아리아/첼로/골드베르크, 비발디 사계, 쇼팽 녹턴, 사티 짐노페디",
  },
  {
    id: "chanson",
    labelEn: "Parisian Chanson & Cafe (10)",
    labelKo: "북카페 & 파리지앵 샹송 (10곡)",
    icon: "Coffee",
    descriptionEn: "Warm French accordion & acoustic cafe guitar across Paris bookstores",
    descriptionKo: "파리 서점 감성의 따스한 아코디언과 어쿠스틱 카페 기타 10곡",
  },
  {
    id: "meditation",
    labelEn: "528Hz Alpha Meditation (10)",
    labelKo: "528Hz 딥포커스 명상 (10곡)",
    icon: "Sparkles",
    descriptionEn: "Solfeggio cognitive frequencies & mindfulness singing bowl sounds",
    descriptionKo: "528Hz 뇌파 동기화 주파수와 싱잉볼 이완 사운드 10곡",
  },
  {
    id: "nature",
    labelEn: "Nature & Rain Sanctuary (10)",
    labelKo: "자연의 소리 & 빗소리 (10곡)",
    icon: "CloudRain",
    descriptionEn: "Library rain, Pacific waves, forest birdsong & mountain streams",
    descriptionKo: "도서관 창가 빗소리, 파도, 숲속 새소리, 계곡물 백색소음 10곡",
  },
];

export const READING_AUDIO_TRACKS: AudioTrack[] = [
  // ==========================================
  // 1. CLASSICAL PIANO & STRINGS (10 Tracks)
  // ==========================================
  {
    id: "bach-air-on-g-string",
    title: "Bach - Air on the G String (BWV 1068)",
    artist: "J.S. Bach (Studio Chamber Strings)",
    category: "classical",
    categoryLabel: "바흐 현악 🎻",
    genreEn: "Classical Masterpieces",
    genreKo: "클래식 명곡",
    src: "/audio/classical/bach-air-on-g-string.mp3",
    duration: "4:32",
    icon: "Music",
  },
  {
    id: "bach-cello-suite",
    title: "Bach - Cello Suite No. 1 in G major (Prelude)",
    artist: "J.S. Bach (Acoustic Solo Cello)",
    category: "classical",
    categoryLabel: "바흐 첼로 🎻",
    genreEn: "Classical Masterpieces",
    genreKo: "클래식 명곡",
    src: "/audio/classical/bach-cello-suite.mp3",
    duration: "3:40",
    icon: "Music",
  },
  {
    id: "bach-goldberg",
    title: "Bach - Goldberg Variations: Aria (BWV 988)",
    artist: "J.S. Bach (Grand Piano Solo)",
    category: "classical",
    categoryLabel: "바흐 골드베르크 🎹",
    genreEn: "Classical Masterpieces",
    genreKo: "클래식 명곡",
    src: "/audio/classical/bach-goldberg.mp3",
    duration: "4:15",
    icon: "Music",
  },
  {
    id: "bach-minuet",
    title: "Bach - Minuet in G major (BWV Anh. 114)",
    artist: "J.S. Bach (Baroque Piano)",
    category: "classical",
    categoryLabel: "바흐 미뉴에트 🎹",
    genreEn: "Classical Masterpieces",
    genreKo: "클래식 명곡",
    src: "/audio/classical/bach-minuet.mp3",
    duration: "2:50",
    icon: "Music",
  },
  {
    id: "vivaldi-spring",
    title: "Vivaldi - Four Seasons: Spring (La Primavera - Allegro)",
    artist: "Antonio Vivaldi (Baroque Chamber Orchestra)",
    category: "classical",
    categoryLabel: "비발디 사계 봄 🌸",
    genreEn: "Classical Masterpieces",
    genreKo: "클래식 명곡",
    src: "/audio/classical/vivaldi-spring.mp3",
    duration: "6:10",
    icon: "Music",
  },
  {
    id: "vivaldi-winter",
    title: "Vivaldi - Four Seasons: Winter (L'Inverno - Allegro)",
    artist: "Antonio Vivaldi (Violin & Strings)",
    category: "classical",
    categoryLabel: "비발디 사계 겨울 ❄️",
    genreEn: "Classical Masterpieces",
    genreKo: "클래식 명곡",
    src: "/audio/classical/vivaldi-winter.mp3",
    duration: "3:30",
    icon: "Music",
  },
  {
    id: "vivaldi-summer",
    title: "Vivaldi - Four Seasons: Summer (L'Estate - Storm Presto)",
    artist: "Antonio Vivaldi (Dynamic Strings Ensemble)",
    category: "classical",
    categoryLabel: "비발디 사계 여름 ⚡",
    genreEn: "Classical Masterpieces",
    genreKo: "클래식 명곡",
    src: "/audio/classical/vivaldi-summer.mp3",
    duration: "4:05",
    icon: "Music",
  },
  {
    id: "chopin-nocturne",
    title: "Chopin - Nocturne in E-flat major, Op. 9 No. 2",
    artist: "Frederic Chopin (Concert Grand Piano)",
    category: "classical",
    categoryLabel: "쇼팽 녹턴 🎹",
    genreEn: "Classical Masterpieces",
    genreKo: "클래식 명곡",
    src: "/audio/classical/chopin-nocturne.mp3",
    duration: "4:32",
    icon: "Music",
  },
  {
    id: "satie-gymnopedie",
    title: "Erik Satie - Gymnopédie No. 1",
    artist: "Erik Satie (Acoustic Piano Lounge)",
    category: "classical",
    categoryLabel: "사티 짐노페디 🎹",
    genreEn: "Classical Masterpieces",
    genreKo: "클래식 명곡",
    src: "/audio/classical/satie-gymnopedie.mp3",
    duration: "3:40",
    icon: "Music",
  },
  {
    id: "beethoven-moonlight",
    title: "Beethoven - Moonlight Sonata (Op. 27 No. 2 - Adagio)",
    artist: "Ludwig van Beethoven (Solo Piano)",
    category: "classical",
    categoryLabel: "베토벤 월광 🎹",
    genreEn: "Classical Masterpieces",
    genreKo: "클래식 명곡",
    src: "/audio/classical/beethoven-moonlight.mp3",
    duration: "5:15",
    icon: "Music",
  },

  // ==========================================
  // 2. PARISIAN CHANSON & CAFE (10 Tracks)
  // ==========================================
  {
    id: "chanson-accordion",
    title: "Breeze of Paris (Bookstore Cafe Chanson)",
    artist: "French Accordion & Acoustic Trio",
    category: "chanson",
    categoryLabel: "북카페 샹송 ☕",
    genreEn: "Parisian Chanson",
    genreKo: "파리지앵 샹송",
    src: "/audio/classical/chanson-accordion.mp3",
    duration: "3:10",
    icon: "Coffee",
  },
  {
    id: "chanson-acoustic",
    title: "Montmartre Sunset (Warm Acoustic Guitar)",
    artist: "Parisian Acoustic Ensemble",
    category: "chanson",
    categoryLabel: "어쿠스틱 카페 🎸",
    genreEn: "Parisian Chanson",
    genreKo: "파리지앵 샹송",
    src: "/audio/classical/chanson-acoustic.mp3",
    duration: "3:25",
    icon: "Coffee",
  },
  {
    id: "chanson-seine-walk",
    title: "Seine River Promenade (Vintage French Waltz)",
    artist: "Paris Accordion & Grand Piano",
    category: "chanson",
    categoryLabel: "센 강 산책 🍷",
    genreEn: "Parisian Chanson",
    genreKo: "파리지앵 샹송",
    src: "/audio/classical/chanson-seine-walk.mp3",
    duration: "3:45",
    icon: "Coffee",
  },
  {
    id: "chanson-saint-germain",
    title: "Saint-Germain Morning Coffee (Jazz Manouche)",
    artist: "Gypsy Swing Cafe Trio",
    category: "chanson",
    categoryLabel: "생제르맹 모닝 ☕",
    genreEn: "Parisian Chanson",
    genreKo: "파리지앵 샹송",
    src: "/audio/classical/chanson-saint-germain.mp3",
    duration: "3:30",
    icon: "Coffee",
  },
  {
    id: "chanson-rue-cler",
    title: "Rue Cler Afternoon Melody (Acoustic Strings)",
    artist: "French Folk Instrumentals",
    category: "chanson",
    categoryLabel: "뤼클레르 오후 🎻",
    genreEn: "Parisian Chanson",
    genreKo: "파리지앵 샹송",
    src: "/audio/classical/chanson-rue-cler.mp3",
    duration: "3:20",
    icon: "Coffee",
  },
  {
    id: "chanson-latin-quarter",
    title: "Latin Quarter Bookstore Vibe (Warm Fingerpicking)",
    artist: "Boutique Cafe Guitars",
    category: "chanson",
    categoryLabel: "라탱 지구 서점 📚",
    genreEn: "Parisian Chanson",
    genreKo: "파리지앵 샹송",
    src: "/audio/classical/chanson-latin-quarter.mp3",
    duration: "3:15",
    icon: "Coffee",
  },
  {
    id: "chanson-champs-elysees",
    title: "Champs-Élysées Twilight (Romantic Musette)",
    artist: "Traditional Musette Accordion",
    category: "chanson",
    categoryLabel: "샹젤리제 황혼 🌆",
    genreEn: "Parisian Chanson",
    genreKo: "파리지앵 샹송",
    src: "/audio/classical/chanson-champs-elysees.mp3",
    duration: "3:40",
    icon: "Coffee",
  },
  {
    id: "chanson-le-marais",
    title: "Le Marais Artisan Cafe (Warm Nylon Solo)",
    artist: "Parisian Solo Classical Guitar",
    category: "chanson",
    categoryLabel: "마레 지구 카페 🥐",
    genreEn: "Parisian Chanson",
    genreKo: "파리지앵 샹송",
    src: "/audio/classical/chanson-le-marais.mp3",
    duration: "3:50",
    icon: "Coffee",
  },
  {
    id: "chanson-provence",
    title: "Provence Lavender Field (French Countryside Waltz)",
    artist: "Acoustic Accordion & Mandolin",
    category: "chanson",
    categoryLabel: "프로방스 라벤더 🌿",
    genreEn: "Parisian Chanson",
    genreKo: "파리지앵 샹송",
    src: "/audio/classical/chanson-provence.mp3",
    duration: "4:00",
    icon: "Coffee",
  },
  {
    id: "chanson-night-breeze",
    title: "Parisian Midnight Serenade (Solo Cello & Accordion)",
    artist: "Chamber Music of France",
    category: "chanson",
    categoryLabel: "파리의 밤 🌙",
    genreEn: "Parisian Chanson",
    genreKo: "파리지앵 샹송",
    src: "/audio/classical/chanson-night-breeze.mp3",
    duration: "3:35",
    icon: "Coffee",
  },

  // ==========================================
  // 3. 528Hz ALPHA MEDITATION (10 Tracks)
  // ==========================================
  {
    id: "meditation-528hz",
    title: "528Hz Alpha Brainwave Deep Reading Focus",
    artist: "Solfeggio Cognitive Research",
    category: "meditation",
    categoryLabel: "528Hz 몰입 독서 🧘",
    genreEn: "528Hz Meditation",
    genreKo: "528Hz 명상",
    src: "/audio/classical/meditation-528hz.mp3",
    duration: "5:00",
    icon: "Sparkles",
  },
  {
    id: "meditation-432hz-miracle",
    title: "432Hz Miracle Tone Mind Rest & Serenity",
    artist: "Harmonic Sacred Sound",
    category: "meditation",
    categoryLabel: "432Hz 이완 명상 🕊️",
    genreEn: "528Hz Meditation",
    genreKo: "528Hz 명상",
    src: "/audio/classical/meditation-432hz-miracle.mp3",
    duration: "5:30",
    icon: "Sparkles",
  },
  {
    id: "meditation-solfeggio-clarity",
    title: "528Hz Solfeggio Mental Clarity & Focus",
    artist: "Binaural Cognitive Soundscape",
    category: "meditation",
    categoryLabel: "528Hz 멘탈 포커스 🧠",
    genreEn: "528Hz Meditation",
    genreKo: "528Hz 명상",
    src: "/audio/classical/meditation-solfeggio-clarity.mp3",
    duration: "4:45",
    icon: "Sparkles",
  },
  {
    id: "meditation-tibetan-bowl",
    title: "Tibetan Singing Bowl Harmonic Resonance",
    artist: "Himalayan Mindfulness Monks",
    category: "meditation",
    categoryLabel: "티베트 싱잉볼 🥣",
    genreEn: "528Hz Meditation",
    genreKo: "528Hz 명상",
    src: "/audio/classical/meditation-tibetan-bowl.mp3",
    duration: "6:00",
    icon: "Sparkles",
  },
  {
    id: "meditation-theta-flow",
    title: "Deep Theta Flow State & Subconscious Quiet",
    artist: "Deep Focus Lab",
    category: "meditation",
    categoryLabel: "세타파 딥 플로우 🌊",
    genreEn: "528Hz Meditation",
    genreKo: "528Hz 명상",
    src: "/audio/classical/meditation-theta-flow.mp3",
    duration: "5:15",
    icon: "Sparkles",
  },
  {
    id: "meditation-zen-garden",
    title: "Zen Garden Water Bamboo & Temple Chimes",
    artist: "Kyoto Meditation Sanctuary",
    category: "meditation",
    categoryLabel: "교토 젠 가든 🎋",
    genreEn: "528Hz Meditation",
    genreKo: "528Hz 명상",
    src: "/audio/classical/meditation-zen-garden.mp3",
    duration: "4:50",
    icon: "Sparkles",
  },
  {
    id: "meditation-astral-serenity",
    title: "Astral Horizon Cosmic Calm & Stillness",
    artist: "Ambient Space Resonance",
    category: "meditation",
    categoryLabel: "코스믹 고요 🌌",
    genreEn: "528Hz Meditation",
    genreKo: "528Hz 명상",
    src: "/audio/classical/meditation-astral-serenity.mp3",
    duration: "5:40",
    icon: "Sparkles",
  },
  {
    id: "meditation-alpha-healing",
    title: "528Hz Cellular Healing & Deep Relaxation",
    artist: "Integrative Sound Medicine",
    category: "meditation",
    categoryLabel: "528Hz 힐링 스트림 ✨",
    genreEn: "528Hz Meditation",
    genreKo: "528Hz 명상",
    src: "/audio/classical/meditation-alpha-healing.mp3",
    duration: "5:10",
    icon: "Sparkles",
  },
  {
    id: "meditation-temple-mindfulness",
    title: "Temple of Stillness Mindfulness Gong",
    artist: "Zen Mindfulness Ensemble",
    category: "meditation",
    categoryLabel: "사원 징 사운드 🔔",
    genreEn: "528Hz Meditation",
    genreKo: "528Hz 명상",
    src: "/audio/classical/meditation-temple-mindfulness.mp3",
    duration: "4:35",
    icon: "Sparkles",
  },
  {
    id: "meditation-celestial-horizon",
    title: "Celestial Floating Body & Mind Release",
    artist: "Pure Frequency Sanctuary",
    category: "meditation",
    categoryLabel: "영혼 이완 명상 🌟",
    genreEn: "528Hz Meditation",
    genreKo: "528Hz 명상",
    src: "/audio/classical/meditation-celestial-horizon.mp3",
    duration: "5:25",
    icon: "Sparkles",
  },

  // ==========================================
  // 4. NATURE & RAIN SANCTUARY (10 Tracks)
  // ==========================================
  {
    id: "nature-rain",
    title: "Gentle Rain on Library Windowpane",
    artist: "Ambient Nature Sanctuary",
    category: "nature",
    categoryLabel: "도서관 빗소리 🌧️",
    genreEn: "Nature Sanctuary",
    genreKo: "자연 빗소리",
    src: "/audio/classical/nature-rain.mp3",
    duration: "6:10",
    icon: "CloudRain",
  },
  {
    id: "nature-ocean",
    title: "Calm Ocean Waves & Horizon Breeze",
    artist: "Coastal Calming Sound",
    category: "nature",
    categoryLabel: "온화한 파도소리 🌊",
    genreEn: "Nature Sanctuary",
    genreKo: "자연 파도소리",
    src: "/audio/classical/nature-ocean.mp3",
    duration: "5:30",
    icon: "CloudRain",
  },
  {
    id: "nature-forest-birdsong",
    title: "Pine Forest Morning Birdsong & Gentle Leaves",
    artist: "Alpine Woodland Sound",
    category: "nature",
    categoryLabel: "숲속 아침 새소리 🌲",
    genreEn: "Nature Sanctuary",
    genreKo: "자연 새소리",
    src: "/audio/classical/nature-forest-birdsong.mp3",
    duration: "4:40",
    icon: "CloudRain",
  },
  {
    id: "nature-mountain-stream",
    title: "Mountain Crystal Stream & Forest Whispers",
    artist: "Highland Water Sounds",
    category: "nature",
    categoryLabel: "계곡물 소리 🏞️",
    genreEn: "Nature Sanctuary",
    genreKo: "자연 계곡물",
    src: "/audio/classical/nature-mountain-stream.mp3",
    duration: "5:15",
    icon: "CloudRain",
  },
  {
    id: "nature-fireplace-thunder",
    title: "Cozy Library Fireplace & Distant Thunder",
    artist: "Warm Hearth Acoustics",
    category: "nature",
    categoryLabel: "벽난로 & 천둥 🪵",
    genreEn: "Nature Sanctuary",
    genreKo: "자연 벽난로",
    src: "/audio/classical/nature-fireplace-thunder.mp3",
    duration: "6:20",
    icon: "CloudRain",
  },
  {
    id: "nature-night-crickets",
    title: "Summer Night Crickets & Starry Sky",
    artist: "Twilight Meadow Sound",
    category: "nature",
    categoryLabel: "밤 귀뚜라미 🦗",
    genreEn: "Nature Sanctuary",
    genreKo: "자연 밤벌레",
    src: "/audio/classical/nature-night-crickets.mp3",
    duration: "4:50",
    icon: "CloudRain",
  },
  {
    id: "nature-bamboo-breeze",
    title: "Bamboo Grove Wind Whispers",
    artist: "Asian Wind Sanctuary",
    category: "nature",
    categoryLabel: "대나무 숲 바람 🎋",
    genreEn: "Nature Sanctuary",
    genreKo: "자연 대나무",
    src: "/audio/classical/nature-bamboo-breeze.mp3",
    duration: "5:05",
    icon: "CloudRain",
  },
  {
    id: "nature-woodland-rain",
    title: "Deep Woodland Rain on Oak Canopy",
    artist: "Ancient Forest Rain",
    category: "nature",
    categoryLabel: "숲속 나뭇잎 비 🌳",
    genreEn: "Nature Sanctuary",
    genreKo: "자연 숲속 비",
    src: "/audio/classical/nature-woodland-rain.mp3",
    duration: "5:45",
    icon: "CloudRain",
  },
  {
    id: "nature-waterfall-mist",
    title: "Serene Waterfall Mist & River Basin",
    artist: "Pure Cascading Stream",
    category: "nature",
    categoryLabel: "폭포 안개 사운드 💦",
    genreEn: "Nature Sanctuary",
    genreKo: "자연 폭포수",
    src: "/audio/classical/nature-waterfall-mist.mp3",
    duration: "5:10",
    icon: "CloudRain",
  },
  {
    id: "nature-sunrise-breeze",
    title: "Horizon Dawn Meadow Birds & Gentle Wind",
    artist: "Early Morning Solitude",
    category: "nature",
    categoryLabel: "새벽 풀밭 바람 🌅",
    genreEn: "Nature Sanctuary",
    genreKo: "자연 새벽바람",
    src: "/audio/classical/nature-sunrise-breeze.mp3",
    duration: "4:30",
    icon: "CloudRain",
  },
];

export const RELAXING_AUDIO_TRACKS = READING_AUDIO_TRACKS;
